### ISSUE TITLE
retail issues

### ISSUE THREAD

**Issue by masterkain** [martinbjeldbak/Shotta#11]
```
1x Shotta/options.lua:361: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@Shotta/options.lua"]:361: in function `InitializeOptions'
[string "@Shotta/main.lua"]:314: in function <Shotta/main.lua:300>
```

**Comment by martinbjeldbak** [comment]
Hi @masterkain I'm on a fix now, will release shortly. Thanks for flagging this!

**Comment by martinbjeldbak** [comment]
Hi @masterkain [v2.0.1](https://github.com/martinbjeldbak/Shotta/releases/tag/v2.0.1) has just been released, can you try updating with your plugin manager of choice and seeing if it's fixed now? Cheers!

**Comment by masterkain** [comment]
thanks, I see no errors now, but is there an option to perform a screenshot at the end of arena/solo/battleground?

**Comment by martinbjeldbak** [comment]
Great idea! I have submitted a suggestion to our feature list on discord for this feature: https://discord.com/channels/1225339543599976539/1282661071919906827 please keep an eye the for any updates.

Going to close this issue as im glad to hear the error has been fixed. Please do raise another issue or post on Discord if you encounter any more issues. Thanks again for logging this.
